version: '3.6'
services:
  db:
    image: postgres
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data:delegated

  mongo_db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: always
    ports:
      - "27017:27017"

  web:
    tty: true
    stdin_open: true
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/wtracker
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mongo_db

volumes:
  mongo-data:
  db_data:
    external: true
