version: '3.6'
services:
  db:
    image: postgres
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data:delegated

  web:
    tty: true
    stdin_open: true
    build: .
    platform: linux/amd64
    command: rails s -b 0.0.0.0
    volumes:
      - .:/wtracker
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
    external: true
