version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0
commands: # a reusable command with parameters
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"

jobs:
  build:
    docker:
      - image: cimg/ruby:2.5.9-node
    steps:
      - greeting:
          to: "build"
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:2.5.9-node
    steps:
      - greeting:
          to: "test"
      - checkout
      - ruby/install-deps
      # Run rspec in parallel
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build