---
http_interactions:
- request:
    method: get
    uri: http://maps.googleapis.com/maps/api/geocode/json?address=10%20Rembrandt,%20East%20Windsor,%20NJ,%2008520&language=en&sensor=false
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Tue, 12 Nov 2013 12:57:37 GMT
      Expires:
      - Wed, 13 Nov 2013 12:57:37 GMT
      Cache-Control:
      - public, max-age=86400
      Access-Control-Allow-Origin:
      - "*"
      Server:
      - mafe
      X-Xss-Protection:
      - 1; mode=block
      X-Frame-Options:
      - SAMEORIGIN
      Alternate-Protocol:
      - 80:quic
      Transfer-Encoding:
      - chunked
    body:
      encoding: US-ASCII
      string: |
        {
           "results" : [
              {
                 "address_components" : [
                    {
                       "long_name" : "10",
                       "short_name" : "10",
                       "types" : [ "street_number" ]
                    },
                    {
                       "long_name" : "Rembrandt Way",
                       "short_name" : "Rembrandt Way",
                       "types" : [ "route" ]
                    },
                    {
                       "long_name" : "East Windsor",
                       "short_name" : "East Windsor",
                       "types" : [ "locality", "political" ]
                    },
                    {
                       "long_name" : "Mercer",
                       "short_name" : "Mercer",
                       "types" : [ "administrative_area_level_2", "political" ]
                    },
                    {
                       "long_name" : "New Jersey",
                       "short_name" : "NJ",
                       "types" : [ "administrative_area_level_1", "political" ]
                    },
                    {
                       "long_name" : "United States",
                       "short_name" : "US",
                       "types" : [ "country", "political" ]
                    },
                    {
                       "long_name" : "08520",
                       "short_name" : "08520",
                       "types" : [ "postal_code" ]
                    }
                 ],
                 "formatted_address" : "10 Rembrandt Way, East Windsor, NJ 08520, USA",
                 "geometry" : {
                    "location" : {
                       "lat" : 40.253859,
                       "lng" : -74.54743490000001
                    },
                    "location_type" : "ROOFTOP",
                    "viewport" : {
                       "northeast" : {
                          "lat" : 40.2552079802915,
                          "lng" : -74.54608591970852
                       },
                       "southwest" : {
                          "lat" : 40.2525100197085,
                          "lng" : -74.54878388029152
                       }
                    }
                 },
                 "partial_match" : true,
                 "types" : [ "street_address" ]
              }
           ],
           "status" : "OK"
        }
    http_version: 
  recorded_at: Tue, 12 Nov 2013 12:57:35 GMT
- request:
    method: get
    uri: http://maps.googleapis.com/maps/api/geocode/json?address=east%20windsor,nj,08520&language=en&sensor=false
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Tue, 10 Dec 2013 18:48:16 GMT
      Expires:
      - Wed, 11 Dec 2013 18:48:16 GMT
      Cache-Control:
      - public, max-age=86400
      Access-Control-Allow-Origin:
      - "*"
      Server:
      - mafe
      X-Xss-Protection:
      - 1; mode=block
      X-Frame-Options:
      - SAMEORIGIN
      Alternate-Protocol:
      - 80:quic
      Transfer-Encoding:
      - chunked
    body:
      encoding: US-ASCII
      string: |
        {
           "results" : [
              {
                 "address_components" : [
                    {
                       "long_name" : "East Windsor",
                       "short_name" : "East Windsor",
                       "types" : [ "locality", "political" ]
                    },
                    {
                       "long_name" : "Mercer",
                       "short_name" : "Mercer",
                       "types" : [ "administrative_area_level_2", "political" ]
                    },
                    {
                       "long_name" : "New Jersey",
                       "short_name" : "NJ",
                       "types" : [ "administrative_area_level_1", "political" ]
                    },
                    {
                       "long_name" : "United States",
                       "short_name" : "US",
                       "types" : [ "country", "political" ]
                    }
                 ],
                 "formatted_address" : "East Windsor, NJ, USA",
                 "geometry" : {
                    "bounds" : {
                       "northeast" : {
                          "lat" : 40.301054,
                          "lng" : -74.481202
                       },
                       "southwest" : {
                          "lat" : 40.216653,
                          "lng" : -74.5794629
                       }
                    },
                    "location" : {
                       "lat" : 40.2677539,
                       "lng" : -74.54025059999999
                    },
                    "location_type" : "APPROXIMATE",
                    "viewport" : {
                       "northeast" : {
                          "lat" : 40.301054,
                          "lng" : -74.481202
                       },
                       "southwest" : {
                          "lat" : 40.216653,
                          "lng" : -74.5794629
                       }
                    }
                 },
                 "types" : [ "locality", "political" ]
              }
           ],
           "status" : "OK"
        }
    http_version: 
  recorded_at: Tue, 10 Dec 2013 18:48:12 GMT
- request:
    method: get
    uri: https://maps.googleapis.com/maps/api/geocode/json?address=10%20Rembrandt,%20East%20Windsor,%20NJ,%2008520&key=<googleapis_key>&language=en&sensor=false
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Sat, 19 Oct 2019 18:57:41 GMT
      Pragma:
      - no-cache
      Expires:
      - Fri, 01 Jan 1990 00:00:00 GMT
      Cache-Control:
      - no-cache, must-revalidate
      Access-Control-Allow-Origin:
      - "*"
      Server:
      - mafe
      X-Xss-Protection:
      - '0'
      X-Frame-Options:
      - SAMEORIGIN
      Server-Timing:
      - gfet4t7; dur=422
      Alt-Svc:
      - quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443";
        ma=2592000,h3-Q043=":443"; ma=2592000
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: |
        {
           "results" : [
              {
                 "address_components" : [
                    {
                       "long_name" : "10",
                       "short_name" : "10",
                       "types" : [ "street_number" ]
                    },
                    {
                       "long_name" : "Rembrandt Way",
                       "short_name" : "Rembrandt Way",
                       "types" : [ "route" ]
                    },
                    {
                       "long_name" : "East Windsor",
                       "short_name" : "East Windsor",
                       "types" : [ "locality", "political" ]
                    },
                    {
                       "long_name" : "Mercer County",
                       "short_name" : "Mercer County",
                       "types" : [ "administrative_area_level_2", "political" ]
                    },
                    {
                       "long_name" : "New Jersey",
                       "short_name" : "NJ",
                       "types" : [ "administrative_area_level_1", "political" ]
                    },
                    {
                       "long_name" : "United States",
                       "short_name" : "US",
                       "types" : [ "country", "political" ]
                    },
                    {
                       "long_name" : "08520",
                       "short_name" : "08520",
                       "types" : [ "postal_code" ]
                    },
                    {
                       "long_name" : "2991",
                       "short_name" : "2991",
                       "types" : [ "postal_code_suffix" ]
                    }
                 ],
                 "formatted_address" : "10 Rembrandt Way, East Windsor, NJ 08520, USA",
                 "geometry" : {
                    "bounds" : {
                       "northeast" : {
                          "lat" : 40.2540114,
                          "lng" : -74.5473743
                       },
                       "southwest" : {
                          "lat" : 40.2538188,
                          "lng" : -74.5476249
                       }
                    },
                    "location" : {
                       "lat" : 40.2539016,
                       "lng" : -74.5474954
                    },
                    "location_type" : "ROOFTOP",
                    "viewport" : {
                       "northeast" : {
                          "lat" : 40.2552640802915,
                          "lng" : -74.5461506197085
                       },
                       "southwest" : {
                          "lat" : 40.2525661197085,
                          "lng" : -74.54884858029151
                       }
                    }
                 },
                 "place_id" : "ChIJJcT1FZ7fw4kR6jTaaCMT7mw",
                 "types" : [ "premise" ]
              }
           ],
           "status" : "OK"
        }
    http_version: 
  recorded_at: Sat, 19 Oct 2019 18:57:41 GMT
recorded_with: VCR 2.9.2
