APP_TITLE: 'WTracker'
AUTOLEAD_EMAIL_PASSWORD: 'password'
AUTOLEAD_EMAIL_USERNAME: 'support@operoinc.com'
AUTOLEAD_FROM_EMAILS: "support1@operoinc.com,support2@operoinc.com,support3@operoinc.com"
AWS_BUCKET_PREFIX: 'managee2e'
COMPANY_NAME: WTRACKER
COMPANY_WEB_ADDRESS: www.wtracker.com
DO_NOT_REPLY_EMAIL: 'donotreply@wtracker.com'
DOMAIN: 'wtracker'
FT_GMAIL_USER_NAME: 'tapoapp@gmail.com'
FT_GMAIL_PASSWORD: 'password'
GMAIL_PASSWORD: 'password'
GMAIL_USER_NAME: 'info@operoinc.com'
JBD: 'murty.jobamatic.com'
JOB_LEADS_EMAIL: 'jobleads@operoinc.com'
JOB_BOARD: Indeed
OPERO_API_PASSWORD: 'password'
PSHID: '110999'
SUPPORT_EMAIL_PASSWORD: 'password'
SUPPORT_FROM_EMAIL: 'support@operoinc.com'
TAPO_WORKERS_COUNT: 1
TAPO_WORKERS_PREFIX: 'tapoworker'
